[package]
name = "png-rs"
version = "0.1.0"
authors = ["Sam Barr <samfbarr@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
luminance = "0.38"
luminance-derive = "0.5"
luminance-windowing = "0.8"
luminance-glfw = "0.12"
glfw = "0.34"
